### ISSUE TITLE
No answer after compiling.

### ISSUE THREAD

**Issue by zallaevan** [normalgamer/Meteors#4]
I have compiled the software using build.bat, but it seems that it only says "Pass 1, Pass 2", no much more. It doesn't run the code. I recommend adding in the readme.md a "How 2 install" section, and a TL;DR for each section.

**Comment by normalgamer** [comment]
The build.bat script will assemble the code using NESASM3, but it won't run it. You'll get two output files, main.fns and main.nes. To run main.nes (the ROM file of the game) you'll have to download a NES emulator (like FCEUX).
